### ISSUE TITLE
[BUG] js_of_ocaml is excessively memory hungry

### ISSUE THREAD

**Issue by JasonGross** [ocsigen/js_of_ocaml#1612] opened 2024-05-09 05:08 UTC
**Describe the bug**

`js_of_ocaml` is very cool!  I use it on CI to generate a webpage.  However, I cannot use it on the new GitHub Actions arm64 MacOS boxes, which have only 7 GB of RAM, because it sometimes eats 8--9 GB RAM to generate a single .js file.  For example [here is a table of build times and memory usages on linux](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991439/job/24130114864):
```
     Time |   Peak Mem | File Name                                         
---------------------------------------------------------------------------
15m11.31s | 8904232 ko | Total Time / Peak Mem                             
---------------------------------------------------------------------------
 4m46.85s | 8808932 ko | ExtractionJsOfOCaml/bedrock2_fiat_crypto.js       
 4m37.20s | 7151532 ko | ExtractionJsOfOCaml/fiat_crypto.js                
 4m30.42s | 8904232 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.js  
 0m25.80s | 3195952 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.byte
 0m25.32s | 3193600 ko | ExtractionJsOfOCaml/bedrock2_fiat_crypto.byte     
 0m24.60s | 2814364 ko | ExtractionJsOfOCaml/fiat_crypto.byte              
 0m00.38s |  102780 ko | ExtractionJsOfOCaml/bedrock2_fiat_crypto.cmi      
 0m00.37s |   98468 ko | ExtractionJsOfOCaml/fiat_crypto.cmi               
 0m00.37s |  102360 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.cmi 
```
It is similar on [mac](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991430/job/24124235290#step:21:27), and a bit better on [debian sid](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991433/job/24124235827#step:24:27).

I [invoke it with](https://github.com/mit-plv/fiat-crypto/blob/c5008e7450bb462f3ad9f0735e45ec751c9d266a/Makefile.standalone#L27-L30) `--source-map --no-inline --enable=effects` and invoke the compiler with ` -package js_of_ocaml -package unix -w -20 -g`

For the near future (until artifacts expire), the [build artifacts page](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991439) contains generated .js files (fiat-html-js-of-ocaml), .ml source files (ExtractionJsOfOCaml-source-master), and compiled files (ExtractionJsOfOCaml-master-ocaml-4.11.1).

**Expected behavior**
I expect there to be a way to make the js_of_ocaml pipeline fit in under 7GB of RAM, possibly with a flag, if necessary.

**Versions**
[js_of_ocaml 5.7.2](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991439/job/24130114864#step:4:38), [ocaml 4.11.1](https://github.com/mit-plv/fiat-crypto/actions/runs/8790991439/job/24130114864#step:5:1904)

**Comment by hhugo** [comment] 2024-05-13 14:00
- `--no-inline` is  no longer necessary (since js_of_ocaml.5.7.0).
- dealing with debug info seems to be slow in your use case. Removing `--source-map` should speed up your build. I'll try to investigate.
- adding `--disable globaldeadcode` should give you a good speedup as well.

With the change mentioned, I the following for `ExtractionJsOfOCaml/bedrock2_fiat_crypto.js` 

```
112.97user 1.26system 1:54.24elapsed 99%CPU (0avgtext+0avgdata 4581104maxresident)k
0inputs+21904outputs (0major+1275732minor)pagefaults 0swaps
```

**Comment by hhugo** [comment] 2024-05-13 14:31
with #1614, one no longer need to disable globaldeadcode, at the cost of extra memory usage.
```
78.16user 1.85system 1:20.13elapsed 99%CPU (0avgtext+0avgdata 6034576maxresident)k
0inputs+19696outputs (0major+1631738minor)pagefaults 0swaps
``` 
I'll try to improve #1614

**Comment by hhugo** [comment] 2024-05-13 14:57
I've updated #1614, I now get 
```
73.86user 1.00system 1:14.87elapsed 99%CPU (0avgtext+0avgdata 4581396maxresident)k
0inputs+19696outputs (0major+1209270minor)pagefaults 0swaps
```

I still need to investigate the sourcemap issue.

Can you test #1614 and confirm it solves part of your issue ?

**Comment by OlivierNicole** [comment] 2024-05-23 08:33
@hhugo Regarding this, I have been working on the sourcemap slowness and will open a PR today.

**Comment by hhugo** [comment] 2024-06-01 21:57
@JasonGross,  any luck with #1614 ?

**Comment by JasonGross** [comment] 2024-06-01 22:04
I have not had a chance to try it, but if it works on your end, I don't see why it would be any different on GitHub Actions.  (The files I linked to are the ones I actually use, not simplified examples .). But I can set up GHA to use the PR.  Should I just clone the repo and `opam pin add .` on that branch?

**Comment by OlivierNicole** [comment] 2024-06-02 14:38
#1617 may help too if the memory consumption happens to be in sourcemaps. I find that it nearly halves the peak memory usage when linking JSOO using itself.

**Comment by hhugo** [comment] 2024-06-10 15:31
@JasonGross, I think you can just do
```
opam pin add js_of_ocaml-compiler https://github.com/ocsigen/js_of_ocaml.git#speedup
```

**Comment by JasonGross** [comment] 2024-06-12 03:21
I've set it up on CI:
[pre](https://github.com/mit-plv/fiat-crypto/actions/runs/9467772244) (specifically [here](https://github.com/mit-plv/fiat-crypto/actions/runs/9467772244/job/26082583136#step:12:446))
[post](https://github.com/mit-plv/fiat-crypto/actions/runs/9476171708?pr=1922) (still in progress)

**Comment by OlivierNicole** [comment] 2024-06-17 12:07
It looks both #1614 and #1617 make both the run time and the peak memory usage worse. I haven’t worked on #1614 but that surprises me a lot in the case #1617. Are these tests runnable on Linux? I may try to inspect them locally.

**Comment by hhugo** [comment] 2024-06-17 13:34
Not all CI jobs have been updated.

Here is what I see for #1614 

>  1m28.92s | 4461616 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.js

**Comment by hhugo** [comment] 2024-06-17 13:38
And for #1617
> 4m47.42s | 5253024 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.js

**Comment by hhugo** [comment] 2024-06-17 13:46
compared to
>   6m08.88s | 7720996 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.js

**Comment by OlivierNicole** [comment] 2024-06-17 14:34
> Not all CI jobs have been updated.
> 
> Here is what I see for #1614
> 
> > 1m28.92s | 4461616 ko | ExtractionJsOfOCaml/with_bedrock2_fiat_crypto.js


I didn’t quite follow which of the many jobs to inspect to find the info, but I trust that your numbers are right.



> @OlivierNicole, I would expect your PR to only affect separate compilation during the link step but I don't think separate compilation is involved here. What part of your PR would improve the situation during whole program compilation ?

I’m honestly not sure. Looking into it.

**Comment by OlivierNicole** [comment] 2024-06-17 15:08
I switched to `` `Stringlit `` and `Yojson.Raw` (rather than `` `String `` and `Yojson.Basic`) because it saves a non-negligible amount of time on the parsing and the writing of the `mappings` fields of source maps (essentially, ``Yojson.Basic.to_string (`String s)`` checks for special characters or Unicode code points in the string, which takes a suprising amount of time and is unnecessary on mappings since they contain only base64 numbers, commas and semicolons.

I’m not sure it explains it all though. Trying to profile locally.

**Comment by JasonGross** [comment] 2024-06-17 23:13
> Are these tests runnable on Linux?

Yes.  The cheapest way to run them is to download any of the artists labeled ExtractionJsOfOCaml-source* from our CI.  These artifacts contain a handful of self-contained .ml files, the ones that we want to turn into .js files.  I gave the flags I use in the initial post.

The expensive way to run the tests is to clone the repo, do `opam install coq`, and then run something like `make js-of-ocaml`

**Comment by OlivierNicole** [comment] 2024-06-18 09:52
I can’t reproduce a significant difference in terms of run time nor profile between master and #1617. The time spent on source maps is negligible compared to the time spent optimizing. I’m starting to suspect that the CI run times have a huge variance.

**Comment by OlivierNicole** [comment] 2024-06-18 14:15
P.S. I’ve done the test on with_bedrock2_fiat_crypto. Peak memory usage is not significantly affected, either.

**Comment by hhugo** [comment] 2024-06-28 09:38
#1614 has been merged. Reopen if you still have issues

**Closed by hhugo** 2024-06-28 09:38 UTC
Labels: bug

**Comment by hhugo** [comment] 2025-05-07 22:43
Many improvement landed on master recently.  On my laptop, I can now compile `bedrock2_fiat_crypto.js` in 26s and 2G of memory
```
/bin/time _build/default/compiler/bin-js_of_ocaml/js_of_ocaml.exe benchmarks/benchmark-fiat-crypto/bedrock2_fiat_crypto.byte --opt 1 --effects=cps
26.47user 0.64system 0:27.13elapsed 99%CPU (0avgtext+0avgdata 2095280maxresident)k
0inputs+22368outputs (0major+535388minor)pagefaults 0swaps
```
