### ISSUE TITLE
Problems with doc page "Export OCaml code to JavaScript"

### ISSUE THREAD

**Issue by bguil** [ocsigen/js_of_ocaml#960] opened 2020-02-02 13:07 UTC
On the documentation page [Export OCaml code to JavaScript](http://ocsigen.org/js_of_ocaml/3.5.1/manual/rev-bindings), I had to modify the example to let it work.

## In the caml code:
`Js.export "myMathLib"` --> `Js_of_ocaml.Js.export "myMathLib"`
without this, I have the error `Error: Unbound module Js`

## In the JS code:
`math.add(2,3)` --> `math.myMathLib.add(2,3)`
without this, I have the error `TypeError: math.add is not a function`

**Comment by hhugo** [comment] 2021-12-22 10:42
The ocaml side has been fixed in 43ded38233c4e1e13427531763b6d3f8cf1d4a6c

For the js side, I suspect you've mixed the two example. At least, I'm not able to reproduce your issue.

**Closed by hhugo** 2021-12-22 10:42 UTC
Labels: documentation
