### ISSUE TITLE
[BUG] `--enable=effects` may cause incorrect compilation results (TypeError: cont is not a function)

### ISSUE THREAD

**Issue by kxc-wraikny** [ocsigen/js_of_ocaml#1589] opened 2024-03-22 10:48 UTC
**Describe the bug**
When building the following code with js_of_ocaml, if `--enable=effects` is specified, execution fails with the error `TypeError: cont is not a function`. If `--enable=effects` is not specified, it runs fine.

https://github.com/kxc-wraikny/jsoo_effects_bug_reproduction/blob/1a387c59e7b78df5986cadcd243d40fb5542edb9/test/jsoo_effects_bug_reproduction.ml

```
$ dune runtest
File "test/dune", line 8, characters 0-105:
 8 | (rule
 9 |  (alias runtest)
10 |  (deps jsoo_effects_bug_reproduction.bc.js)
11 |  (action
12 |   (run %{bin:node} %{deps})))
[07:44:43.085] [SUCCESS] (1/3) plus - should return 2 by 1, 1
[07:44:43.085] [SUCCESS] (2/3) plus - should return 3 by 1, 2
/Users/wk/Projects/jsoo_effects_bug_reproduction/_build/default/test/jsoo_effects_bug_reproduction.bc.js:5730
     throw err;
     ^

TypeError: cont is not a function
    at Timeout._onTimeout (/Users/wk/Projects/jsoo_effects_bug_reproduction/_build/default/test/jsoo_effects_bug_reproduction.bc.js:44956:43)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.10.0
```

repo: https://github.com/kxc-wraikny/jsoo_effects_bug_reproduction/

**Expected behavior**
The built js code executed correctly without errors.

**Versions**
- The OCaml toplevel, version 5.1.0
- Js_of_oacml 5.7.1
- Node.js v20.10.0

**Comment by vouillon** [comment] 2024-03-22 11:33
There is a bug in `prr`.
In file `fut.ml`, the definition of `tick` should be:
```ocaml
let tick ~ms =
  fut @@ Jv.Promise.create @@ fun res _rej ->
  ignore (Jv.apply (Jv.get Jv.global "setTimeout") Jv.[| callback ~arity:1 res; of_int ms |])
```

**Comment by haochenx** [comment] 2024-03-22 12:14
@vouillon many thanks for taking time to look into it. I just applied your suggested fix and now the test passes!

As `prr` is merely a fork (and out-of-date version) of `brr` and it seems that `brr` [still has the same code](https://github.com/dbuenzli/brr/blob/06d3a6d0789a60329b89917c70a26f69ae1ad891/src/fut.ml#L58C1-L60C81), we will open a bug report on `brr` as well.

Do you mind to share how you traced the root cause down? We found it quite difficult to trace such bugs as stack trace isn't very helpful (even if source map is on..)

**Comment by vouillon** [comment] 2024-03-22 14:28
This looked like a calling convention mismatch (an OCaml function called from JavaScript as if it was a JavaScript function).
The error was in some `prr` code related to promises (function `Jv.Promise.create`), and indeed in a callback.
And the stack trace mentions `Timeout._onTimeout`, so I searched for a `setTimeout`.

**Comment by haochenx** [comment] 2024-03-23 16:03
Wow that's impressive and thanks for the hint!

Fixing `fut.ml` made our codebase all worked again. I think this issue can be closed as it's now apparent that it's due to a misuse instead of a bug in jsoo.

(@kxc-wraikny opened this issue on behalf of our team but @kxc-wraikny is taking a break until Mar 28;
so I will be handing the communication until then.)

**Closed** 2024-03-23 18:43 UTC
Labels: bug

**Comment by dbuenzli** [comment] 2024-03-28 01:17
Thanks, this has been fixed in https://github.com/dbuenzli/brr/commit/5b1dbedc1fb98ef553dcacffe2695bd403a66cd1. It seems I missed that in [the PR](https://github.com/dbuenzli/brr/pull/43) by Jérôme and subsequent commit of mine that was supposed to sanitize all that.

**Comment by haochenx** [comment] 2024-04-12 18:36
Thank you all!
