### ISSUE TITLE
When using `--source-map` System error occurs.

### ISSUE THREAD

**Issue by jordwalke** [ocsigen/js_of_ocaml#484] opened 2016-06-05 20:24 UTC
We upgraded js_of_ocaml, and now we get the following error, but only when including `--source-map` flag:

```
js_of_ocaml: Error: Sys_error("Is a directory")

```

I'm having a hard time getting back traces, even with `OCAMLRUNPARAM=b` but I will report back with more information if I can get those working.

**Comment by jordwalke** [comment] 2016-06-05 22:00
Sadly, I was unable to get stack trace printing. Even with `OCAMLRUNPARAM=b`. I wonder why.

**Comment by cristianoc** [comment] 2016-06-08 02:39
This is with pinned latest master. Same trace with 2.7.
```
Raised by primitive operation at file "pervasives.ml", line 355, characters 12-37
Called from file "util.cppo.ml", line 86, characters 2-23
Called from file "js_output.ml", line 1072, characters 36-55
Called from file "list.ml", line 55, characters 20-23
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "js_output.ml", line 1068, characters 14-256
Called from file "driver.ml", line 346, characters 2-44
Called from file "jsoo_compile.ml", line 39, characters 9-13
Re-raised at file "jsoo_compile.ml", line 39, characters 44-45
Re-raised at file "jsoo_compile.ml", line 45, characters 10-13
Called from file "jsoo_compile.ml", line 119, characters 6-336
```

**Comment by hhugo** [comment] 2016-06-08 16:49
Can you retry with the lastest js_of_ocaml. You should get a proper error. 
see https://github.com/ocsigen/js_of_ocaml/commit/231bb68f4006c1fac51faac2f51632fb9f6d0657

**Comment by jordwalke** [comment] 2016-06-11 19:47
Yes, now I get a proper error message, thank you.

**Comment by jordwalke** [comment] 2016-06-11 22:00
However, I don't think the error should even be happening. When I include the `--source-map` flag, I get a strange error:

```
js_of_ocaml: Error: Cannot read content of /Users/jwalke/github/MyProject/someDir/.
```

**Comment by hhugo** [comment] 2016-06-11 23:44
Can you provide your bytecode program (privately if you prefer) ? I'm not able to reproduce this issue.

**Comment by hhugo** [comment] 2016-06-14 09:42
fixed by https://github.com/ocsigen/js_of_ocaml/commit/efebf4d09eb8d87cb24b7e22fea975e6d4e3a988

**Closed by hhugo** 2016-06-14 09:42 UTC

**Comment by jordwalke** [comment] 2016-06-14 09:55
Thank you!
