### ISSUE TITLE
Issue installing jsoo4 with esy

### ISSUE THREAD

**Issue by phated** [ocsigen/js_of_ocaml#1237] opened 2022-02-01 19:56 UTC
I tried upgrading Binaryen.ml to use js_of_ocaml v4.0.0 and our CI is failing for Windows: https://github.com/grain-lang/binaryen.ml/runs/5016130428?check_suite_focus=true

This is running in esy because I don't believe the opam repository is synced with v4.0.0 yet (see our opam run: https://github.com/grain-lang/binaryen.ml/runs/5016130531?check_suite_focus=true)

Anything I can do to help get this fixed? I'd really like to upgrade us to v4

**Comment by hhugo** [comment] 2022-02-01 23:31
https://github.com/fdopen/opam-repository-mingw has not been updated for 7days. Maybe raise an issue there ...

**Comment by phated** [comment] 2022-02-01 23:44
@hhugo esy doesn't pull from that repository. I understand that is why the opam CI is failing.

It seems the issue is related to a `mkdir` that happens during install?
```
Copying to _destdir/.C/Users/runneradmin/.esy/3__________________________________________________________/s/opam__s__js__of__ocaml_compiler-opam__c__4.0.0-24eb8e7a/lib/js_of_ocaml-compiler/META

    Error: mkdir:

_destdir/.C/Users/runneradmin/.esy/3__________________________________________________________/s/opam__s__js__of__ocaml_compiler-opam__c__4.0.0-24eb8e7a/lib/js_of_ocaml-compiler:

    No such file or directory

    error: command failed: "dune" "install" "-p" "js_of_ocaml-compiler" "--create-install-files" "js_of_ocaml-compiler" (exited with 1)
    esy-build-package: exiting with errors above...
```

Are you doing an explicit mkdir somewhere?

**Comment by hhugo** [comment] 2022-02-02 07:53
Isn't it `dune install` that is failing in your case ?

**Comment by phated** [comment] 2022-02-02 07:55
It might be, that;'s the command that is being logged (though, I don't know enough to know if that's logging the actual command that errors). Why is the `dune install` command in the `build:` stanza of the opam file instead of the `install:` stanza?

**Comment by phated** [comment] 2022-02-02 07:56
I'm also hoping to get @eduardorfs to help me look at this when he has time. This is a blocker on Grain being able to update to JSOO v4 since we only install with `esy` and need to support Windows.

**Comment by TheSpyder** [comment] 2022-04-26 03:51
I'm also having an issue installing v4 (I'd like to use the new `target-env` option) with esy. I'm not sure if it's the same problem - I'm on macOS 12 monterey not windows - I can log a new issue if necessary.

```
info building @opam/js_of_ocaml-ppx@opam:4.0.0@bca7f5ce
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/js_of_ocaml-ppx@opam:4.0.0
    # esy-build-package: pwd: /Users/spyder/.esy/3/b/opam__s__js__of__ocaml_ppx-opam__c__4.0.0-8c4b8dc3
    # esy-build-package: running: 'dune' 'build' '-p' 'js_of_ocaml-ppx' '-j' '4' '--promote-install-files=false' '@install'
    (cd tools/version && /Users/spyder/.esy/3_________________________________________________________________/i/ocaml-4.14.0-942b87e4/bin/ocaml -I +compiler-libs /Users/spyder/.esy/3/b/opam__s__js__of__ocaml_ppx-opam__c__4.0.0-8c4b8dc3/_build/.dune/default/tools/version/dune.ml)
    fatal: not a git repository (or any of the parent directories): .git
    # esy-build-package: running: 'dune' 'install' '-p' 'js_of_ocaml-ppx' '--create-install-files' 'js_of_ocaml-ppx'
    /usr/local/bin/opam var prefix > /tmp/dune_7d1cc1_output
    [ERROR] Opam has not been initialised, please run `opam init'
    error: command failed: 'dune' 'install' '-p' 'js_of_ocaml-ppx' '--create-install-files' 'js_of_ocaml-ppx' (exited with 1)
    esy-build-package: exiting with errors above...
```

That appears to be this code which runs git, but it has an exception handler so I'm not whether it is really the source of the failure 🤔 
https://github.com/ocsigen/js_of_ocaml/blob/5b6201c4094fe3c6dab81a75c609bd70924df6fb/tools/version/dune#L5-L9

**Comment by hhugo** [comment] 2022-04-26 08:13
The issue is not the git version, it is `[ERROR] Opam has not been initialised`. See
https://github.com/ocaml/dune/issues/5455

**Comment by TheSpyder** [comment] 2022-04-26 08:18
Ah. I’ll subscribe to that for updates, thanks!

**Comment by hhugo** [comment] 2022-05-23 10:59
Should be solved with dune.3.2. Closing. Open a new issue if you sill have issues

**Closed by hhugo** 2022-05-23 10:59 UTC
