### ISSUE TITLE
Wrong syntax in doc

### ISSUE THREAD

**Issue by Tyruiop** [ocsigen/js_of_ocaml#426] opened 2016-02-27 01:06 UTC
It seems there might be an issue in the doc of this page https://ocsigen.org/js_of_ocaml/api/Lwt_js_events on the "Defining a thread that waits for ESC key on an element" example which uses the camlp4 lwt syntax.

**Comment by hhugo** [comment] 2016-03-28 20:43
Can you be more precise ? what is the issue ?

**Comment by vasilisp** [comment] 2016-03-29 10:53
I think that the issue is mixing Camlp4 bindings (`lwt x = e in e'`) with PPX JS attributes (`e##.x`). It should be fixed by 8523fef.

**Closed** 2016-03-29 13:56 UTC
