### ISSUE TITLE
Sourcemaps for .re (Reason) files

### ISSUE THREAD

**Issue by jchavarri** [ocsigen/js_of_ocaml#716] opened 2018-11-20 09:46 UTC
I'm setting up a small project to learn about js_of_ocaml with incr_dom, and using the Reason syntax (https://github.com/jchavarri/incr_dom_reason/).

Everything works 🎉 but the sourcemaps for Reason files seem to be broken:

![sourcemaps](https://user-images.githubusercontent.com/220424/48764925-4bcea300-ecb1-11e8-97fc-09970295868f.gif)

They seem to point to the `.re.ml` files that are generated on the build folder.

Is there any configuration that I can use to fix this? cc @jordwalke

**Comment by jordwalke** [comment] 2018-11-21 08:45
Last time I checked the source maps (even for .ml) need a little more work to be generally usable. But for this particular bug, I'm surprised it's happening. I saw .re sourcemaps working somewhat correctly a long time ago but that was before Dune was the one generating them. The issue is that Dune first generates a .ml file (which is just a raw serialized AST that happens to have an .ml extension) to feed to ocamlc. Normally you'd just supply the .re file as input directly to ocamlc. Even so, I'm surprised because I would think that the locations embeded in the output `.ml` serialized AST are actually pointing to the `.re` file, and those locations are where the the source maps are generated from so I'd think it would be correct. You could probably put a hack in jsoo in the source maps generation that just knows to redirect all `'.re.ml'` to `.re`.

**Comment by jchavarri** [comment] 2018-11-21 10:06
@jordwalke Thanks. I confirm I have tested the same project but using `.ml` files with the existing config, and I can see sourcemaps being generated fine (I wanted to be sure I wasn't somehow using a wrong config).

I'll investigate the fix you mention.

**Comment by jchavarri** [comment] 2018-11-25 14:07
Update: I started a [simpler project](https://github.com/jchavarri/hello-jsoo-esy/) that includes just the bare configuration of jsoo, dune and esy, and source maps in that case work beautifully:

![sourcemaps](https://user-images.githubusercontent.com/220424/48980012-a017bf80-f0c3-11e8-9b6e-7ae20eccc38a.gif)

So it seems to be an isolated issue of the original repo I mentioned in the description. That repo [includes a bunch of ppxs](https://github.com/jchavarri/incr_dom_reason/blob/master/src/dune#L4), not sure if it might be related.

**Comment by hhugo** [comment] 2018-12-02 05:38
I believe this is an issue with how dune handle some reason files.

The steps goes as follow:
1. parse the source `name.re` with refmt and output `name.re.ml` (marshaled ocaml ast with correct locations)
2. apply some ppx on `name.re.ml` and output `name.re.pp.ml` (locations are now wrong and refer to name.re.ml)

Passing args `-loc-filename src/name.re` when applying ppx seems to fix the issue.

cc @rgrinberg, @diml

**Comment by jordwalke** [comment] 2018-12-03 08:07
Great find. I imagine that would also end up causing other issues too.

**Comment by diml** [comment] 2018-12-03 13:44
Hmm, actually maybe ppxlib is trying to be too clever here. When the filename read from the marshaled ast file doesn't match what ppxlib thinks the filename is, it rewrites the AST with the new name. At least, we shouldn't rewrite the AST unless `-loc-filename` is passed explicitly.

**Comment by hhugo** [comment] 2018-12-09 08:03
Ppxlib has been fixed. Closing.

**Closed by hhugo** 2018-12-09 08:03 UTC
Labels: bug

**Comment by jordwalke** [comment] 2018-12-09 12:19
thanks
